# Generated by Django 3.1.4 on 2021-03-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20210315_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='date',
        ),
    ]
