# Generated by Django 3.1.4 on 2021-03-21 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_entryitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
