# Generated by Django 3.1.4 on 2021-04-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20210321_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryitem',
            old_name='entry',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
