# Generated by Django 3.1.4 on 2021-04-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_auto_20210403_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='balance',
        ),
    ]
